### ISSUE TITLE
HTTP 302 Code

### ISSUE THREAD

**Issue by fantom-x** [yetisno/ACD-JAPI#5]
Have been playing with the API for a few days now and all of a sudden the Amazon servers started responding with HTTP Code 302 (see below) (in Nodes.downloadFile). If I take the URL from "Location" and paste it into a browser then I can download the file without having to log in: the URL is already pre-authenticated. Have you seen this too? This HTTP code is not handled in the API at this time...

```
DefaultHttpResponse(chunked: false)
HTTP/1.1 302 Found
Date: Thu, 12 May 2016 02:16:50 GMT
Location: https://cd-na-prod-content.s3.amazonaws.com/{TRUNCATED}
Signature={TRUNCATED}
Server: Amazon-Cloud-Drive
x-amzn-RequestId: {TRUNCATED}
Content-Length: 0
Connection: keep-alive
```

**Comment by yetisno** [comment]
Ok, Let's clear that!

The point is...
1. it can't download with `Nodes.downloadFile`, because HTTP 302 is present?
2. it can download, but the redirect code 302 response is without auth, feel it's unusual?

**Comment by fantom-x** [comment]
It fails to download when response is 302. I set "follow redirect" to true and it started downloading.

**Comment by yetisno** [comment]
YES, it should follow redirect! I didn't in this case before. i'll fix it, thank you!

**Comment by fantom-x** [comment]
Why not just change it here?

[.setFollowRedirect(false)](https://github.com/yetisno/ACD-JAPI/blob/master/src/main/java/org/yetiz/lib/acd/ACDSession.java#L27)

**Comment by yetisno** [comment]
wow, i miss it! Thank you!
